language: python

python:
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get update
    - sudo apt-get install python3-pip
    - pip3 install virtualenv
    - virtualenv env
    - source env/bin/activate

install:
    - sudo apt-get install python3-tk
    - pip3 install -r requirements.txt

script: python3 cell_tests.py  # run_tests.py

after_failure: echo "Test failed"
after_success:
  - coverage combine
  - coverage run cell_tests.py
  - coverage report -m modules/*.py
